# Generated by Django 4.2.16 on 2025-01-15 22:27

import catasto.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=catasto.models.directory_path)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('numero_progressivo', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('approvato', models.BooleanField(default=False)),
                ('data_approvazione', models.DateField(blank=True, null=True)),
                ('numero_protocollo', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_protocollo_generale', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_protocollo_settore', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('trascrizione', models.TextField(blank=True, max_length=10000, null=True)),
                ('richiedente', models.CharField(blank=True, max_length=100, null=True)),
                ('destinatario', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
            },
        ),
        migrations.CreateModel(
            name='Fascicolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foglio', models.CharField(max_length=20)),
                ('particella', models.CharField(max_length=20)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('costruttore', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('documenti', models.ManyToManyField(related_name='fascicoli', to='catasto.documento')),
            ],
            options={
                'verbose_name': 'Fascicolo',
                'verbose_name_plural': 'Fascicoli',
            },
        ),
        migrations.CreateModel(
            name='Pratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('documenti', models.ManyToManyField(related_name='pratiche', to='catasto.documento')),
            ],
            options={
                'verbose_name': 'Pratica',
                'verbose_name_plural': 'Pratiche',
            },
        ),
        migrations.CreateModel(
            name='TipoCostruzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Costruzione',
                'verbose_name_plural': 'Tipi Costruzione',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipi Documento',
            },
        ),
        migrations.CreateModel(
            name='Subalterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('documenti', models.ManyToManyField(related_name='subalterni', to='catasto.documento')),
                ('fascicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catasto.fascicolo')),
                ('pratiche', models.ManyToManyField(related_name='subalterni', to='catasto.pratica')),
            ],
            options={
                'verbose_name': 'Subalterno',
                'verbose_name_plural': 'Subalterni',
            },
        ),
        migrations.AddField(
            model_name='fascicolo',
            name='pratiche',
            field=models.ManyToManyField(related_name='fascicoli', to='catasto.pratica'),
        ),
        migrations.AddField(
            model_name='fascicolo',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catasto.tipocostruzione'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catasto.tipodocumento'),
        ),
    ]
