# Generated by Django 4.2.16 on 2025-01-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catasto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fascicolo',
            name='documenti',
            field=models.ManyToManyField(blank=True, related_name='fascicoli', to='catasto.documento'),
        ),
        migrations.AlterField(
            model_name='fascicolo',
            name='pratiche',
            field=models.ManyToManyField(blank=True, related_name='fascicoli', to='catasto.pratica'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='documenti',
            field=models.ManyToManyField(blank=True, related_name='pratiche', to='catasto.documento'),
        ),
        migrations.AlterField(
            model_name='subalterno',
            name='documenti',
            field=models.ManyToManyField(blank=True, related_name='subalterni', to='catasto.documento'),
        ),
        migrations.AlterField(
            model_name='subalterno',
            name='pratiche',
            field=models.ManyToManyField(blank=True, related_name='subalterni', to='catasto.pratica'),
        ),
    ]
