# Generated by Django 4.2.16 on 2025-01-18 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catasto', '0002_alter_fascicolo_documenti_alter_fascicolo_pratiche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fascicolo',
            name='documenti',
        ),
        migrations.RemoveField(
            model_name='fascicolo',
            name='pratiche',
        ),
        migrations.RemoveField(
            model_name='pratica',
            name='documenti',
        ),
        migrations.RemoveField(
            model_name='subalterno',
            name='documenti',
        ),
        migrations.RemoveField(
            model_name='subalterno',
            name='pratiche',
        ),
        migrations.AddField(
            model_name='documento',
            name='subalterno',
            field=models.ManyToManyField(blank=True, to='catasto.subalterno'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='fascicolo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pratiche', to='catasto.fascicolo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pratica',
            name='subalterno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pratiche', to='catasto.subalterno'),
        ),
    ]
