# Generated by Django 4.2.16 on 2025-02-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catasto', '0003_remove_fascicolo_documenti_remove_fascicolo_pratiche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='subalterno',
        ),
        migrations.AddField(
            model_name='documento',
            name='fascicolo',
            field=models.ManyToManyField(blank=True, related_name='documenti', to='catasto.fascicolo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='pratiche',
            field=models.ManyToManyField(blank=True, related_name='documenti', to='catasto.pratica'),
        ),
        migrations.AddField(
            model_name='documento',
            name='subalterni',
            field=models.ManyToManyField(blank=True, related_name='documenti', to='catasto.subalterno'),
        ),
    ]
