# Generated by Django 5.2.6 on 2025-10-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catasto', '0004_remove_documento_subalterno_documento_fascicolo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='fascicolo',
        ),
        migrations.AddField(
            model_name='documento',
            name='fascicoli',
            field=models.ManyToManyField(blank=True, related_name='documenti', to='catasto.fascicolo'),
        ),
    ]
